services:
  search-grpc:
    image: ghcr.io/tranduy1dol/kotoba-search-engine:latest
    ports: ["50051:50051"]
    env_file: env/.env.local
    volumes:
      - search_index:/data/index

  backend:
    image: ghcr.io/tranduy1dol/kotoba-core:latest
    ports: ["8080:8080"]
    env_file: env/.env.local
    depends_on:
      - search-grpc

volumes:
  search_index: